# Generated by Django 5.0.6 on 2024-05-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.TextField(max_length=255, unique=True)),
                (
                    'description',
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
