# Generated by Django 4.1.3 on 2022-11-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cinema",
            new_name="Movie",
        ),
    ]
