# Generated by Django 5.0.3 on 2024-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "movies"},
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
