# Generated by Django 5.0.3 on 2024-03-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Movie", "verbose_name_plural": "Movies"},
        ),
    ]
