# Generated by Django 5.0.6 on 2024-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
