# Generated by Django 5.0.4 on 2024-04-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cinema",
            new_name="Movie",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="name",
            new_name="title",
        ),
    ]
