# Generated by Django 5.0.6 on 2024-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
