# Generated by Django 4.1.4 on 2022-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["title"], "verbose_name_plural": "movies"},
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
