# Generated by Django 4.1.3 on 2022-11-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
