# Generated by Django 5.0.6 on 2024-05-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_options_alter_movie_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "Movies"},
        ),
    ]
