# Generated by Django 5.0.6 on 2024-07-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movies'},
        ),
    ]
