# Generated by Django 5.0.6 on 2024-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movies'},
        ),
    ]
