# Generated by Django 5.0.1 on 2024-01-10 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_rename_model_cinema"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cinema",
            new_name="Movie",
        ),
    ]
