# Generated by Django 5.0.3 on 2024-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
