# Generated by Django 4.2.3 on 2023-07-24 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_alter_movie_description"),
    ]

    operations = []
