# Generated by Django 4.2.3 on 2023-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_auto_20230724_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
