# Generated by Django 5.0.6 on 2024-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(default="Some description", max_length=255),
            preserve_default=False,
        ),
    ]
