# Generated by Django 4.2.7 on 2023-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
    ]
