# Generated by Django 5.0.6 on 2024-05-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
    ]
