# Generated by Django 4.2.3 on 2023-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
