# Generated by Django 4.2 on 2024-02-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_rename_cinema_movie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "Movies"},
        ),
    ]
